Rename test output directory

diff --git a/warptempo_renderas b/warptempo_renderas
--- a/warptempo_renderas
+++ b/warptempo_renderas
@@ -9,22 +9,27 @@ if [[ "$1" == help ]] || [[ "$1" == -h ]] || [[ "$1" == --help ]]; then
 	echo
 	echo "   Usage: "$(basename "$0")" alternate_title <warpmarkers> <settings>"
 	echo
-	echo "The default inputs are .warpmarkers and .settings. Outputs will be placed in alternate_versions."
+	echo "The default inputs are .warpmarkers and .settings. Outputs will be placed in test."
 	exit
+fi
+
+if [[ -f test ]]; then
+	echo "Error: A file called test exists."
+	exit 1
 fi
 
 alternate_title="$1"
 warpmarkers_file="${2:-"$(ls .warpmarkers *.warpmarkers 2>/dev/null | head -n 1)"}"
 settings_file="${3:-"$(ls .settings *.settings 2>/dev/null | head -n 1)"}"
 
-mkdir -p alternate_versions/"$(dirname "$alternate_title")"
+mkdir -p test/"$(dirname "$alternate_title")"
 
-cp -f "$warpmarkers_file" alternate_versions/"$alternate_title".warpmarkers
-cp -f "$settings_file" alternate_versions/"$alternate_title".settings
+cp -f "$warpmarkers_file" test/"$alternate_title".warpmarkers
+cp -f "$settings_file" test/"$alternate_title".settings
 
-sed -i "s|title=.*|title=\"alternate_versions\/$alternate_title\"|" alternate_versions/"$alternate_title".settings
+sed -i "s|title=.*|title=\"test\/$alternate_title\"|" test/"$alternate_title".settings
 
-"$(dirname "$0")"/warptempo alternate_versions/"$alternate_title".warpmarkers alternate_versions/"$alternate_title".settings
+"$(dirname "$0")"/warptempo test/"$alternate_title".warpmarkers test/"$alternate_title".settings
 
 
 
