Set upper and lower bounds for tempo

diff --git a/warptempo b/warptempo
--- a/warptempo
+++ b/warptempo
@@ -336,7 +336,14 @@ while IFS= read -r line; do
 			tempo_scale="${tempo#*\*}"
 			tempo="${tempo_initial}*${tempo_scale}"
 		else
-			tempo="$(printf "%.2f\n" "$(echo "$tempo" | bc -l)")"
+			tempo_initial="$(printf "%.2f\n" "$(echo "$tempo" | bc -l)")"
+			tempo=$tempo_initial
+		fi
+		if [[ "$(echo "$tempo_initial > 9.99" | bc -l)" == 1 ]]; then
+			echo "Error: Tempo greater than 9.99 ($line)." && exit 1
+		fi
+		if [[ "$(echo "$tempo <= 0" | bc -l)" == 1 ]]; then
+			echo "Error: Tempo less than or equal to 0 ($line)." && exit 1
 		fi
 	elif [[ "$tempo" != [0-9]* ]]; then
 		if [[ ! "$tempo" =~ ^[a-z]\.[a-z0-9]{2}$ ]]; then
@@ -511,13 +518,16 @@ for index in "${!warpmarkers[@]}"; do
 		unadjusted_target_frame="$(printf "%.0f\n" "$(echo "$previous_target_frame+(($source_frame-$previous_source_frame)/(($label_tempo)*$scale))" | bc -l)")"
 		label_tempo_multiplier="$(echo "($unadjusted_target_frame-$previous_target_frame)/($target_frame-$previous_target_frame)" | bc -l)"
 		if [[ "$label_tempo" == *\** ]]; then
-			label_tempo_base=$(echo "$label_tempo" | cut -d \* -f1)
-			label_tempo_scale=$(echo "$label_tempo" | cut -d \* -f2)
-			label_tempo_string="$label_tempo_base*$(printf "%06.4f\n" "$(echo "$label_tempo_scale*$label_tempo_multiplier" | bc -l)")"
+			label_tempo_initial=$(echo "$label_tempo" | cut -d \* -f 1)
+			label_tempo_scale=$(echo "$label_tempo" | cut -d \* -f 2)
+			label_tempo_string="$label_tempo_initial*$(printf "%06.4f\n" "$(echo "$label_tempo_scale*$label_tempo_multiplier" | bc -l)")"
 		else
 			label_tempo_string="$label_tempo*$(printf "%06.4f\n" "$label_tempo_multiplier")"
 		fi
-		
+		label_tempo_final_multiplier=$(echo "$label_tempo_string" | cut -d \* -f 2)
+		if [[ "$(echo "$label_tempo_final_multiplier > 9.9999" | bc -l)" == 1 ]]; then
+			echo "Error: Label tempo final multipler greater than 9.9999 ($warpmarker)." && exit 1
+		fi
 		line="$warpmarker_time|$label ~=$label_tempo_string $(printf "%09.0f\n" $previous_source_frame) $(printf "%09.0f\n" $previous_target_frame) $previous_target_time_ms $previous_target_time_fps"
 	fi
 	
